#!/bin/bash
export TODOTXT_VERBOSE=0
action=$1
shift
function compute_kanbans {
   local sed_expr="sed -e 's/.*kanban:\([[:alpha:]]\+\).*/\1/g'"
   local kanbans_expr="$TODO_SH ls kanban: | grep kanban: | $sed_expr  | sort | uniq"
   eval "$kanbans_expr"
}

case $action in
do)
    line=$1
    $TODO_SH kanban unmark $line
    $TODO_SH command do $line
    ;;
mark)
    line=$1
    kanban=$2
    $TODO_SH kanban unmark $line
    $TODO_SH command append $line "kanban:$kanban"
    ;;
unmark)
    line=$1
    sed -i.bak "$line s/kanban:[[:graph:]]*//" $TODO_FILE
    ;;
ls)
    # cat("\033[1;33mFooBar\033[0m"]")
    echo "Backlog:"
    $TODO_SH -p ls | grep -v kanban: | grep -v "^[[:digit:]]\+ x "
    echo ""

    for kanban in `compute_kanbans`
    do
        echo "$kanban:"
        $TODO_SH -p ls | grep kanban:$kanban | sed -e "s/kanban:[[:graph:]]*//g"
        echo ""
    done

    echo "Done:"
    $TODO_SH listdone
    echo ""
    ;;
lsa)
    $TODO_SH kanban ls

    echo "Archive:"
    $TODO_SH listdone done
    echo ""
    ;;
usage|help)
    echo "   $(basename $0) action [ITEM#] [TAG]"
    echo "     Kanban actions:"
    echo ""
    echo "       do ITEM#"
    echo "         Remove kanban tag and mark as done the task on line ITEM#"
    echo "       ls"
    echo "         Print Kanban items"
    echo "       lsa"
    echo "         Print Kanban items (with Archive section for done tasks in done.txt"
    echo "       unmark ITEM#"
    echo "         Remove the kanban tag from the task on line ITEM#"
    echo "       mark ITEM# TAG"
    echo "         Add (possibly replacing) the kanban tag TAG to the task on line ITEM#"
    echo "       usage|help"
    echo "         Print usage message"
    echo "       *"
    echo "         Passed on to todo.sh"
    exit
    ;;
*)
    $TODO_SH $action $@
    ;;
esac
