#!/bin/bash
action=$1
shift

case $action in
"usage")
    echo "   $(basename $0) [action]"
    echo "     List all done tasks"
    echo "     listdone actions (default is todo):"
    echo ""
    echo "       all"
    echo "         Print all done tasks in both todo.txt and done.txt"
    echo "       done"
    echo "         Print all done tasks in just done.txt"
    echo "       todo"
    echo "         Print all done tasks in todo.txt"
    echo "       usage"
    echo "         Print out this usage message"
  exit
  ;;
all)
    export TODOTXT_VERBOSE=0
    $TODO_SH -p lsa  | grep "^[[:digit:]]* x "
    ;;
done)
    export TODOTXT_VERBOSE=0
    $TODO_SH -p listfile done.txt  | grep "^[[:digit:]]* x "
    ;;
todo|*)
    # grep "^x" $TODO_FILE
    export TODOTXT_VERBOSE=0
    $TODO_SH -p ls  | grep "^[[:digit:]]* x "
    ;;
esac
