" Last change:	2008 May 21
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" if $USER == "m1tld01"
"     let place = "work"
" elseif $USER == "trevorld"
"     let place = "home"
" endif


" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" Useful Settings
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
set nocompatible " Use Vim settings instead of Vi, must be first
" set autoread            " Refresh buffer if file modified externally
set backspace=indent,eol,start " allows backspacing in insert mode
if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  " set backupdir-=.
  " set backupdir^=~/tmp,/tmp
  " set backup		" keep a backup file
  set nobackup
endif
set diffopt+=iwhite     " ignore whitespace when diffing
set expandtab           " insert spaces instead of tabs
set history=50		" keep 50 lines of command line history
set ignorecase          " ignore cases while searching
set incsearch		" do incremental searching
set number              " show line numbers
set ruler		" show the cursor position all the time
set shell=/bin/bash
set shiftwidth=4        " tabs will insert 4 spaces
set showcmd		" display incomplete commands
set spell
set scs                 " don't ignore case if enter uppercase letters
set smarttab            " insert spaces instead of tabs
set vb                  " set visual beep
if &t_Co > 2 || has("gui_running")
  syntax on             " syntax highlighting when terminal has colors
  set hlsearch          " switch highlighting on last used search partern
endif
" assume if vim is called that background is dark
if &t_Co > 2 && !has("gui_running")
  set background=dark
endif

try
" " pathogen easy install vim modules
"     source ~/src/vim/bundle/vim-pathogen/autoload/pathogen.vim
"     execute pathogen#infect('~/src/vim/bundle/{}')
" vim-plug
  source ~/a/media/software/vim/bundle/vim-plug/plug.vim
  call plug#begin('~/a/media/software/vim/bundle')
  Plug 'editorconfig/editorconfig-vim'
  Plug 'Rykka/InstantRst'
  Plug 'Rykka/riv.vim'
  Plug 'vim-scripts/LaTeX-Suite-aka-Vim-LaTeX'
  Plug 'vim-scripts/utl.vim'
  Plug 'vim-scripts/Vim-R-plugin'
  Plug 'vim-scripts/VOom'
  Plug 'vim-utils/vim-troll-stopper'
  Plug 'drmikehenry/vim-fontsize'
  Plug 'tpope/vim-fugitive'
  Plug 'luochen1990/rainbow'
  let g:rainbow_active = 1
  Plug 'scrooloose/syntastic'
  Plug 'chrisbra/csv.vim'
  call plug#end()
catch
    " do nothing
endtry


" greater XDG compliance
" should probably set defaults
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
" set runtimepath=$XDG_CONFIG_HOME/vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$XDG_CONFIG_HOME/vim/after
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" Useful maps
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" map Y mvy$`v      " Default is illogical, should be to end of line 

" copy into and paste from clipboard
map <Leader>y "+y
map <Leader>Y "+Y
map <Leader>p "+p
map <Leader>P "+P
map <Leader>a :% y + " copy entire file

map <Leader>c :silent ! latex % > /dev/null & <CR> " Compile while editing
map <Leader>C :silent ! Rnw2pdf % > /dev/null & <CR> " Compile while editing

" scroll down file with spacebar
map <space> <c-f>

" undo an automatic line break
imap <c-a> <Esc>kJA
map <Leader>en :setlocal spell spelllang=en_us   " Turn english spell check
map <Leader>eo :setlocal spell spelllang=eo_XX   " Turn esperanto spell check

map <Leader>k <C-W>k:bd<Enter>
map <Leader>j <C-W>j:bd<Enter>

" useful maps for Rnoweb files to switch between Latex-suite and vim-r-plugin
map <Leader>r :set filetype=r<CR>:set syntax=rnoweb<CR>
map <Leader>t :set filetype=tex<CR>:set syntax=rnoweb<CR>
" let g:vimrplugin_underscore = 1
let vimrplugin_assign = 0
" let vimrplugin_assign = 0

let g:vimrplugin_latexcmd = "texi2dvi -c -p" 
let maplocalleader = ","
" no smart quotes in latex
let g:Tex_SmartQuoteOpen = '"'
let g:Tex_SmartQuoteClose = '"'
let g:Tex_DefaultTargetFormat = "pdf"
let g:Tex_ViewRule_pdf = "okular"
let g:riv_fold_auto_update = 0

" useful to spread spaces
map <Leader>s i<space><Esc>la<space><Esc>h

" compile rst files
map <Leader>rh :! rst2html % %<.html <Enter>
map <Leader>rp :! rst2latex % %<.tex; texi2dvi -c -p %<.tex <Enter>

" useful maps for writing Re-Structured Text
if has("python")
    map <Leader>- :call Section_Header('-', "below")<Enter>
    map <Leader>_ :call Section_Header('-', "above_below")<Enter>
    map <Leader>` :call Section_Header('~', "below")<Enter>
    map <Leader>~ :call Section_Header('~', "above_below")<Enter>
    map <Leader>= :call Section_Header('=', "below")<Enter>
    map <Leader>+ :call Section_Header('=', "above_below")<Enter>
elseif has("autocmd")
    au Bufenter *.{Rst,rst,RST} map <Leader>- yyp:s/./-/g<Enter>:highlight clear Search<Enter>
    au Bufenter *.{Rst,rst,RST} map <Leader>~ yyp:s/./\~/g<Enter>:highlight clear Search<Enter>
    au Bufenter *.{Rst,rst,RST} map <Leader>= yyp:s/./=/g<Enter>:highlight clear Search<Enter>
    au BufEnter *.{R,pl,py,sh} map <Leader>= yyp:s/./=/g<Enter>:highlight clear Search<Enter>0xxi##<Esc>
    au BufEnter *.{R,pl,py,sh} map <Leader>- yyp:s/./-/g<Enter>:highlight clear Search<Enter>0xxi##<Esc>
    au BufEnter *.{R,pl,py,sh} map <Leader>~ yyp:s/./\~/g<Enter>:highlight clear Search<Enter>0xxi##<Esc>
endif

" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" Useful commands
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
com! Kwbd enew|bw #|bp
com! Kwbn enew|bw #|bn
com! Kwbp enew|bw #|bp
com! Undiff set nodiff | set noscrollbind | set foldcolumn=0

" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" Useful Autocommands
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection,  Use the default filetype settings
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  augroup myAUTOCMDs
    au!
    autocmd Bufenter *.prg set filetype=eviews
    autocmd BufNewFile *.prg set filetype=eviews
    autocmd BufEnter .Rprofile set filetype=r
    autocmd BufRead,BufNewFile,BufEnter *.{R,r} set filetype=r
    "Let us use LSS (Latex Symbol Selector) with out .tex and .Rnw files
    autocmd BufEnter *.tex imap <F8> <Esc>:silent !lss &<cr>a
    autocmd BufEnter *.Rnw imap <F8> <Esc>:silent !lss &<cr>a

  augroup END

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
    au!
    autocmd FileType text setlocal textwidth=79  " Set text file width to 79
    set formatoptions=1
    " When editing a file, always jump to the last known cursor position.
    autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$") |
      \   exe "normal g`\"" |
      \ endif
      " automatically change directories to the file's directory
    autocmd BufEnter * cd %:p:h
  augroup END

else
  set autoindent		" always set autoindenting on

endif " has("autocmd")

" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" custom Latex-Suite style mappings and settings for my Rnoweb and Latex files
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
if exists("*IMAP") && has("autocmd") 
  augroup MyIMAPs
    au!
    au VimEnter * call IMAP('<<', "<<<++>>>=\<CR><++>\<CR>@\<CR><++>", "rnoweb")
    au VimEnter * call IMAP('<<', "<<<++>>>=\<CR><++>\<CR>@\<CR><++>", "tex")
    au VimEnter * call IMAP('@@', "@\<CR><++>\<CR><<<++>>>=", "tex")
    au VimEnter * call IMAP('@@', "@\<CR><++>\<CR><<<++>>>=", "rnoweb")
    au VimEnter * call IMAP('--', " <- ", "r")
    au VimEnter * call IMAP('--', " <- ", "rhelp")
    au VimEnter * call IMAP('--', " <- ", "rnoweb")
    au VimEnter * call IMAP('`V', "\text{Var}", "tex")
    "let us use the Math BF plugin instead of opening the Buffer menu
    autocmd BufWinEnter *.tex imap <C-B> <Plug>Tex_MathBF
    autocmd BufWinEnter *.Rnw imap <C-B> <Plug>Tex_MathBF
  augroup END

  "IMPORTANT: grep will sometimes skip displaying the file name if you
  "search in a single file. This will confuse latex-suite.  Set your grep
  "program to always generate a file-name.
  set grepprg=grep\ -nH\ $*

  " convert \times to \cdot easily
  map <Leader>. :% s/\\times/\\cdot/g<CR>
  map <Leader>b :% s/mathbf/mathbb/g<CR>
  map <Leader>B :% s/mathbb/mathbf/g<CR>

endif

" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" Custom functions
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if has("python")

function! LJ()
python << EOF
import vim
html_string = '''
<!-- <lj-cut text="Read More">  </lj-cut>                                        -->
<!-- <img src="http://www.example.com/image.jpg" alt="title or description" />   -->
<!-- <a href="http://www.example.com/">This is a link to an example website.</a> -->
<!-- <lj user="exampleusername">                                                 -->
<!-- <b>Bold</b> <i>Italic</i> <u>Underline</u> <tt>Monospace</tt>                -->
<!-- <del>Striked text</del> <center>Centered text</center>                      -->
<table cellspacing="25">
<tr>
<td>

</td><td>

</td>
</table>
'''
vim.current.buffer[0:0] = html_string.splitlines()
vim.command('set filetype=html')
EOF
endfunction

function! Section_Header(section_char, type)
python << EOF
import re
import vim
section_char = vim.eval('a:section_char') # non-alphanumeric character: i.e. '-'
type         = vim.eval('a:type')         # either "below" or "above_below"
line = vim.current.line
row = vim.current.window.cursor[0] - 1 # python index starts at zero
length_line = len(line)
if not length_line:
    raise ValueError("Line must have a length greater than zero")
#### check section_char
if re.match('\w', section_char):
    raise ValueError("The first argument, section_char," + \
                     "must be a non-alphanumeric character")
starting_whitespace = re.split('\S', line)[0]
length_whitespace = len(starting_whitespace)
if length_whitespace:
    first_non_whitespace_characters = re.split('\s*', line)[1]
else:
    first_non_whitespace_characters = re.split('\s*', line)[0]
first_char = first_non_whitespace_characters[0]
try: 
    second_char = first_non_whitespace_characters[1]
except:
    second_char = ' '              # assume the second character was a space

if re.match('\w', first_char):     # starts with alphanumeric character
    length_section = length_line - length_whitespace
    header_line = starting_whitespace + (section_char * length_section)
else:                              # does not start with alphanumeric character
    length_section = length_line - length_whitespace - 2
    header_line = starting_whitespace + first_char + second_char + \
                 (section_char * length_section)
print(header_line)
## detect if line above and below start with ``comment``
del vim.current.buffer[row]
if type=="below":
    vim.current.buffer[row:row] = [line, header_line]
elif type=="above_below":
    vim.current.buffer[row:row] = [header_line, line, header_line]
else:
    raise ValueError('The 2nd argument, type, \
                     must either be "below" or "above_below"')
EOF
endfunction

function! VerticalLetters(...)
python << endpython
import re, string, vim
nArgs = int(vim.eval("a:0"))
if nArgs > 0:
    nLines = int(vim.eval("a:1"))
else:
    nLines = 1
if nArgs > 1:
    use_upper_case = int(vim.eval("a:2"))
else:
    use_upper_case = 0
if nArgs > 2:
    if use_upper_case:
        start = re.search(vim.eval("a:3"), string.ascii_uppercase).start()
    else:
        start = re.search(vim.eval("a:3"), string.ascii_lowercase).start()
else:
    start = 0

nColumns = 1
current_line = vim.current.window.cursor[0] - 1
current_column = vim.current.window.cursor[1]
for ii in range(nLines):
    row = current_line + ii
    number = ii + start
    line = vim.current.buffer[row]
    if use_upper_case:
        myline = line[:current_column] + string.ascii_uppercase[number] + line[current_column+nColumns:]
    else:
        myline = line[:current_column] + string.ascii_lowercase[number] + line[current_column+nColumns:]
    vim.current.buffer[row] = myline

endpython
endfunction

function! VerticalNumbers(...)
python << endpython
import vim
nArgs = int(vim.eval("a:0"))
if nArgs > 0:
    nLines = int(vim.eval("a:1"))
else:
    nLines = 1

if nArgs > 1:
    nColumns = int(vim.eval("a:2"))
else:
    nColumns = 1

if nArgs > 2:
    start = int(vim.eval("a:3"))
else:
    start = 1

current_line = vim.current.window.cursor[0] - 1
current_column = vim.current.window.cursor[1]
for ii in range(nLines):
    row = current_line + ii
    number = (("%." + "%d" % nColumns) + "d") % (start + ii)
    line = vim.current.buffer[row]
    myline = line[:current_column] + number + line[current_column+nColumns:]
    vim.current.buffer[row] = myline

endpython
endfunction

endif

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
" let &guioptions = substitute(&guioptions, "t", "", "g")

" Don't use Ex mode, use Q for formatting
map Q gq

" This is an alternative that also works in block mode, but the deleted
" text is lost and it only works for putting the current register.
"vnoremap p "_dp
